### ISSUE TITLE
A has become time-invariant compared to HIPPO

### ISSUE THREAD

**Issue by ZiweiHe** [HazyResearch/state-spaces#21]
Hi,

Thanks for your excellent work!
In the [HIPPO](https://proceedings.neurips.cc/paper/2020/file/102f0bb6efb3a6128a3c750dd16729be-Paper.pdf) paper, the transition matrix A of SSM is time-variant, but has become time-invariant in s4 model. I didn't find any theories/experiments that discuss why it still works. 
Can you kindly share your thoughts?

Thanks again,
Ziwei

**Comment by albertfgu** [comment]
Great question! This was a subtlety that was left out of the S4 paper, because it was originally an empirical finding that I didn't understand theoretically. I have since been able to explain it through the lens of HiPPO theory, and will be releasing a preprint in a few weeks with a discussion of this and other generalizations.

**Comment by albertfgu** [comment]
If you haven't seen it already, this phenomenon has been explained in the preprint [HTTYH](https://arxiv.org/abs/2206.12037)
