### ISSUE TITLE
Should the A, B, C, dt parameters be set to be trainable?

### ISSUE THREAD

**Issue by chenweize1998** [HazyResearch/state-spaces#24]
Hi! 

When I was checking the code, I found that for most of the experimental configurations for S4, the A, B, C, dt parameters are not set to be trainable, while I originally thought that these parameters are trained in S4 presented in the paper. I don't know if I understand it correctly, but isn't this setting similar to HiPPO if these parameters are not trained? Or do you have any empirical findings on this?

Thanks!

**Comment by albertfgu** [comment]
For which configurations were they not set to trainable? For most of our best results, we do set them to be trainable. We will fix the configs if they're incorrect.

The end of Section 4 of the paper has some minor ablations with the parameters being trainable or not; setting them to be trainable generally improves performance a little, and I have since found other settings where training them helps even more.

**Comment by albertfgu** [comment]
They are supposed to be trainable. Could you point to where in the config indicates that they are not trainable? How are you running the code and where does it indicate that they are not trainable?
