### ISSUE TITLE
Controlling Large Memory Usage on GPU

### ISSUE THREAD

**Issue by mdr223** [HazyResearch/state-spaces#84]
Hi there!

I am trying to train a basic S4D model on an A10G GPU (g5.24xlarge EC2 instance). I copied the model definition in `state-spaces/examples.py` and configured it with the following parameters:
- `input_dim`: 7
- `output_dim`: 2
- `model_dim`: 64
- `dropout`: 0.2
- `num_layers`: 6
- `prenorm`: false

On device, the model weights take up ~700 MiB of memory. I then pass in batches of dimension `(B, L, D) = (256, 1801, 7)` with `dtype=np.float32`, which brings the total memory on device to ~1 GiB.

Once I execute the forward pass with my model by calling `model(batch)` I see a large increase in the GPU memory. The total used memory goes from ~ 1 GiB all the way up to ~10 GiB. If I try to scale to a batch size of 512 I will typically hit CUDA out-of-memory errors.

Right now this is a fairly large blocker for me, because my corpus is on the order of TB in size, and iterating over all of it in an epoch in a timely manner requires setting larger batch sizes (e.g. 1024, 2048, or even 4096). I was wondering if you might have any idea as to why the memory increases so much? or know if there are ways I can try to decrease the memory utilization?

I'm currently using the pykeops cauchy kernel (I've had issues getting the `python setup.py install` to work in my docker image) and the default `measure` for S4D. I'm not sure if using the custom CUDA kernel or switching the measure might help with decreasing the memory footprint?

Any advice would be much appreciated!

**Comment by albertfgu** [comment]
The memory usage you're seeing is expected. When running an actual training step (forward + backward pass) the GPU memory is usually dominated by storing the activations. These activations have shape `(batch size, sequence length, model dim)` (times number of layers), which provides a rough heuristic of how much memory it needs. For example, the [S4 LRA config](https://github.com/HazyResearch/state-spaces/blob/main/configs/experiment/lra/s4-lra-pathx.yaml) is 6 layers by `(16, 16384, 256)` (product about `6.7e7` activations per layer) and fills up most of an A100's 40GB RAM. In order to fit a batch size of 4096, you're asking for 6 layers by `(4096, 1800, 64)` (product about `4.7e8`), which is nearly 10x as much memory. This explains why you're running out of RAM at around 512 batch size.

As a simple test, you can remove all of the S4 layers of your model and have only feed-forward components and you'll still run out of memory at those batch sizes.
Ultimately it sounds like training on your corpus simply needs more computational resources.

**Comment by mdr223** [comment]
Thanks for replying so quickly! That makes a lot of sense, I mostly just wanted to check if I was doing something wrong or if there were any easy wins around this, but I'm glad that it is the expected behavior.
