### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by lucadellalib** [HazyResearch/state-spaces#85]
Hi,

congratulations for the great work! I'm trying to run S4 on a big dataset but I eventually get out of memory error even with a batch size of 1. I noticed that GPU memory usage keeps increasing across batches and epochs, hence I suspect there might be a memory leak. Here is a script for reproducibility. On my machine I have a base memory usage ~1153MB which keeps increasing of 2MB every ~10 seconds. On the contrary, if I use a linear layer instead of S4 the memory usage stays constant. Any ideas on how to fix it?
```
import torch

from s4 import S4


if __name__ == "__main__":
    torch.manual_seed(0)

    batch_size = 4
    sequence_length = 8
    input_size = 200
    state_size = 64

    model = S4(input_size, state_size, transposed=False).cuda()
    #model = torch.nn.Linear(input_size, input_size).cuda()

    while True:
        input = torch.rand(batch_size, sequence_length, input_size).cuda()
        model(input)
```

**Comment by albertfgu** [comment]
We have seen memory leaks with the `pykeops` package, which is probably a bug in the package. Are you currently using this? The best way to avoid this is using the custom CUDA extension. Alternatively if you're using S4D you can probably disable the pykeops package, which may use slightly more memory but shouldn't leak.

**Comment by tlasmanbotch** [comment]
Hello! I am also experiencing a memory leak using S4 with the custom CUDA extension. Similar to the post above, the memory continuously increases after each forward pass and across epochs. When I remove the S4 blocks from my forward pass, the leak disappears. 

Would you be able to help debug this leak? Alternatively, do you have a sense of where this leak could be originating? I'm inexperienced with C++ but can attempt to debug.

**Comment by tlasmanbotch** [comment]
Hello! I am also experiencing a memory leak despite using the custom CUDA extension. Specifically, this occurs when using sequences of varying lengths during training. When training with all sequences of the same length I experience static memory usage of around 25K MB. However, when sequences vary in length due to data augmentation, I experience an increase of ~2MB on each forward pass.

Would you have any suggestions on how correct this leak? It is highly specific to training with sequences of varying lengths. Thanks in advance for the help!

**Comment by tlasmanbotch** [comment]
After an extensive search, it seems like this is resulting specifically from the function `torch.rfft`, and therefore is beyond the scope of the S4 repository. Sorry about that!

**Comment by albertfgu** [comment]
That is very strange, I haven't noticed it before. It's also odd if it happens only with variable length sequences. These are some questions I had:
- When you say "sequences vary in length across batches", do you mean that the shape of the input tensor changes per batch, or that the shape is constant (set to the max length) and there is an additional mask passed in?
- If using masking, what happens if the mask is removed (e.g. comment out any masking logic)?
- Are you using S4 or S4D?

**Comment by tlasmanbotch** [comment]
Here's the [related issue](https://github.com/pytorch/pytorch/issues/94893) I opened with some sample code to reproduce. Responses to your questions below:

- Yes, the input tensor shapes change within items of a batch along with items across batches. As a simple example, here are two batches: 1) an input tensor of shape (1, 1202, 768) and 2) an input tensor of shape (1, 1829, 768)
- Masking was removed for these checks
- I have been using S4. Thus far, S4D has been too memory-intensive for the size of my input data (tokens varying around 10K in length)

**Comment by albertfgu** [comment]
S4 does not handle variable-length sequences as well, so that might be it. Do you see log messages of the form "kernel length doubling from X to Y"? It might be caching some extra tensors without freeing them, although it should stop doing that once it reaches the maximum sequence length in the dataset.

S4D memory usage should be ok even without a custom kernel, but if your sequences are very long then it might pose a problem. The pykeops option for S4D should save memory, have you tried that? To isolate the problem better, can you try S4D (with or without pykeops) and make the model smaller to fit in memory, and see if the memory leakage issue still occurs?

**Comment by albertfgu** [comment]
Nevermind, it looks like you completely isolated the problem to just `torch.fft.rfft` without the S4 layers. Very nice find!
